name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main  # o master, según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambia esto a tu región de AWS

      # Primero, configuramos la política del bucket para acceso público
      - name: Make S3 bucket public
        run: |
          aws s3api put-bucket-policy --bucket ${{ secrets.S3_BUCKET }} --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "PublicReadGetObject",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::${{ secrets.S3_BUCKET }}/*"
              }
            ]
          }'

      - name: Deploy to S3
        run: |
          echo "Deploying to bucket: ${{ secrets.S3_BUCKET }}"
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md" \
            --exclude ".gitignore" \
            --acl public-read \
            --cache-control "max-age=86400" \
            --metadata-directive REPLACE \
            --content-type "text/html" \
            --exclude "*" \
            --include "*.html" \
            --include "*.css" \
            --include "*.js" \
            --include "*.jpg" \
            --include "*.jpeg" \
            --include "*.png" \
            --include "*.gif" \
            --include "*.ico" \
            --include "*.svg" \
            --include "*.txt"

      - name: Set content type for specific files
        run: |
          # Configurar content-type para CSS
          aws s3 cp s3://${{ secrets.S3_BUCKET }} s3://${{ secrets.S3_BUCKET }} \
            --exclude "*" --include "*.css" \
            --content-type "text/css" \
            --metadata-directive REPLACE \
            --acl public-read \
            --recursive

          # Configurar content-type para JavaScript
          aws s3 cp s3://${{ secrets.S3_BUCKET }} s3://${{ secrets.S3_BUCKET }} \
            --exclude "*" --include "*.js" \
            --content-type "application/javascript" \
            --metadata-directive REPLACE \
            --acl public-read \
            --recursive

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
